# Generated by Django 3.2.8 on 2021-10-08 15:29

import django.contrib.sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210927_1754'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customsite',
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name='ontologyfilemodel',
            name='upload',
            field=models.FileField(upload_to='ontologies'),
        ),
    ]
